---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: "Uninstall Docker packages."
      ansible.builtin.apt:
        name:
          - "docker-ce"
          - "docker-ce-cli"
          - "docker-ce-rootless-extras"
          - "docker-compose-plugin"
          - "docker-scan-plugin"
        state: absent

    - name: "Remove /etc/docker/key.json."
      ansible.builtin.file:
        path: "/etc/docker/key.json"
        state: absent

    - name: "Remove /etc/apt/sources.list.d/docker.list."
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/docker.list"
        state: absent

    # There doesn't seem to be any gpg key associated with docker (i.e. running
    # apt-key list shows only keys from *@ubuntu.com.

    - name: "Use the vfs storage driver in the Molecule context."
      ansible.builtin.copy:
        content: |
          {
              "storage-driver": "vfs"
          }
        dest: "/etc/docker/daemon.json"
