---
name: Molecule Test

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_ASYNC_DIR: "/tmp/.ansible_async"
    strategy:
      fail-fast: false
      matrix:
        image:
          - "ubuntu1804"
          - "ubuntu2004"
          - "ubuntu2204"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_options: --debug
          molecule_command: test
        env:
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_IMAGE: ${{ matrix.image }}
